# Generated by Django 4.1.3 on 2022-11-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_tasks_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Pending'), (1, 'Complete')], default=0),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
